- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: DNS Server List
          dellemc.sfs.sfs_dns:
            server_list: ["1.1.1.1", "3.3.3.3", "2.2.2.2"]
            address_family: "inet"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result
