- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: Nodes Handler
          dellemc.sfs.sfs_nodes:
            action:  "nodehandler"       # ['nodehandler', 'blink', 'unblink', 'reboot', 'rollback', 'factorydefault']
            node_id: "VB9D06E"
            name: "Leaf01"
            description: "Ansible_test"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result
