- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: Port breakout configuration
          dellemc.sfs.sfs_port_breakout:
            target_port: "VB9D06E:phy-port1/1/27"
            fanout_profile: "4X10GE"
            name: "interface_27"
            description: "Description for Interface22"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result
