- hosts: all
  collections: 
    - dellemc.sfs
  gather_facts: no  
  tasks:
        
    - name: Provision Configs
      block:

            - name: sfs_network
              dellemc.sfs.sfs_network:
                network_name: "sfs_network"
                network_id: "Leaf-test-GeneralPurpose"
                vlan_min: 752
                vlan_max: 752
                qos_priority: "Platinum"
                network_type: "GeneralPurpose"
                network_description: "SFS Network Create Test From Ansible-ddddd"
                state: "present"
              register: result
  
            - name: Update Network
              dellemc.sfs.sfs_network:
                network_id: "My_L3_ROUTED_Network_Id_1"
                network_name: "My_L3_ROUTED_Network_Name_1"
                network_description: "My_L3_ROUTED_Network_Description_1"
                network_type: "L3_ROUTED"
                qos_priority: "Iron"
                address_family: "inet"
                prefix_length: 24
                ip_address_list: ["192.168.1.2", "192.168.1.4"]
                helper_address: ["10.10.10.10", "11.11.11.11"]
                gateway_ip_address: ["192.168.1.3"]
                route_map: "routemap1"
                state: "present"
              register: result

 
            - name: Update VXLAN Network
              dellemc.sfs.sfs_network:
                network_id: "My_VXLAN_Network_Id"
                vlan_min: 400
                vlan_max: 400
                qos_priority: "Iron"
                network_type: "VXLAN"
                virtual_network: "vnet1"
                network_name: "My_VXLAN_Network_Id"
                originator: "vCenter_user"
                network_description: "My_VXLAN_Network_Description"
                state: "present"
              register: result


            - name: MULTIRACK L3 VLAN
              dellemc.sfs.sfs_network:
                network_id: "SREEJITHNETWORK1"
                network_name: "Network1"
                network_description: "My_L3 VLAN_Network_Description_1"
                vlan_max: 401
                vlan_min: 401
                qos_priority: "Iron"
                network_type: "MULTIRACK_L3_VLAN"
                rack_settings: [{ RackID: "6298f46c-b8a8-4548-8bfb-14ee34303147", AddressFamily: "inet", PrefixLen: 24, GateWayIpAddress: ["10.1.1.254"],
               IpAddressList: ["10.1.1.1", "10.1.1.2"], HelperAddress: ["10.10.10.10", "10.11.11.11"] }]
                state: "present"
              register: result

    - name: Debug the result
      debug: var=result
