- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Get Validation Errors
      block:
        - name: Validation Errors
          dellemc.sfs.sfs_validation_errors:
          register: result

    - name: Debug the result
      debug: var=result
