- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: Prefix List Setup
          dellemc.sfs.sfs_prefix_list:
            name: "uplink-prefix"
            description_string: "uplinkPrefixListDescription"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result
