#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfs_snmp
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: configure sfs_snmp
short_description: Configure SNMP server host on Dell SmartFabric Services.
description:
  - This module is used to manage SNMP server host.
author: Ranjith Sunkesula <Ranjith_Senkesula@Dellteam.com>
options:
  host_ipaddress:
    description:
      - Configures the SNMP host IP address.
    type: str
    required: False
  address_family:
    description:
      - Configures the address family.
    type: str
    required: False
  snmp_version:
    description:
      - Configures the SNMP version.
    type: str
    required: False
  community:
    description:
      - Configures the community or username based on the SNMP version.
    type: str
    required: False
  snmp_securitylevel:
    description:
      - Configures the SNMP security details.
    type: str
    required: False
  state:
    description:
      - The state the configuration should be left in.
    type: str
    default: present
    required: False
"""
EXAMPLES = '''
Copy below YAML into a playbook (e.g. play.yml) and run as follows:

#$ ansible-playbook -i inventory play.yaml
- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: SNMP Server
          dellemc.sfs.sfs_snmp:
            host_ipaddress: "192.168.5.3"
            address_family: "inet"
            snmp_version: "v3"
            community: "v3community"
            snmp_securitylevel: "noauth"
            state: "present"
          register: result

    - name: Debug the result
      debug: var=result
'''


from ansible_collections.dellemc.sfs.plugins.module_utils.sfs.sfs import SFSConfig, extract_id_value
from ansible.module_utils.basic import AnsibleModule


class SFSSNMP(SFSConfig):
    def __init__(self):
        argument_spec = {
            'state': {
                'type': 'str',
                'default': "present",
                'required': False
            },
            'host_ipaddress': {
                'type': 'str',
                'required': False
            },
            'address_family': {
                'type': 'str',
                'required': False
            },
            'snmp_version': {
                'type': 'str',
                'default': "v1",
                'required': False,
                'choices': ['v1', 'v2c', 'v3']
            },
            'community': {
                'type': 'str',
                'required': False
            },
            'snmp_securitylevel': {
                'type': 'str',
                'default': "noauth",
                'required': False,
                'choices': ['noauth', 'auth', 'priv']
            }
        }

        module = AnsibleModule(argument_spec=argument_spec)
        SFSConfig.__init__(self, module)
        self.payload_arg_map = {
            'HostIpAddress': 'host_ipaddress',
            'AddressFamily': 'address_family',
            'SNMPVersion': 'snmp_version',
            'Community': 'community',
            'SNMPSecurityLevel': 'snmp_securitylevel'}

        self.path = "NetworkFabricGlobalConfig/SnmpHosts"
        self.resource_id = self.module.params['host_ipaddress']


if __name__ == "__main__":
    SFSSNMP().execute_module()
