#!/usr/bin/env python
# pylint: disable=consider-using-f-string
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfs_fabric_replace
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: configure_sfs_fabric_replace
short_description: Configure node replace on Dell SmartFabric Services.
description:
  - This module is used for switch replacement in the fabric.
author: Ranjith Sunkesula <Ranjith_Senkesula@Dellteam.com>
options:
  old_service_tag:
    description:
      - Configures the valid service tag of the switch that needs to be replaced.
    type: str
    required: False
  new_service_tag:
    description:
      - Configures the service tag of the new switch.
    type: str
    required: False
  state:
    description:
      - The state the configuration should be left in.
    type: str
    default: present
    required: False
"""
EXAMPLES = '''
Copy below YAML into a playbook (e.g. play.yml) and run as follows:

#$ ansible-playbook -i inventory play.yaml
- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: Fabric Replace Nodes
          dellemc.sfs.sfs_fabric_replace:
            old_service_tag: "HMXBPK2"
            fabric_id: "66e7c2b7-78b7-4be2-ab3c-36fababee4d9"
            new_service_tag: "97JBJ23"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result

'''


from ansible_collections.dellemc.sfs.plugins.module_utils.sfs.sfs import SFSConfig, extract_id_value
from ansible_collections.ansible.netcommon.plugins.module_utils.network.restconf import (
    restconf,)
from ansible.module_utils.basic import AnsibleModule


class SFSFabricReplace(SFSConfig):
    def __init__(self):
        argument_spec = {
            'state': {
                'type': 'str',
                'default': "present",
                'required': False
            },
            'new_service_tag': {
                'type': 'str',
                'required': False
            },
            'old_service_tag': {
                'type': 'str',
                'required': False
            },
            'fabric_id': {
                'type': 'str',
                'required': False
            }

        }
        module = AnsibleModule(argument_spec=argument_spec)
        SFSConfig.__init__(self, module)
        self.payload_arg_map = {
            'NewServiceTag': 'new_service_tag',
            'OldServiceTag': 'old_service_tag'
        }

        self.path = "Fabrics('%s')/Fabrics.ReplaceNode" % (self.module.params['fabric_id'])
        self.resource_id = self.module.params['new_service_tag']


if __name__ == "__main__":
    SFSFabricReplace().execute_module()
