#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfs_acl_mapping
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: configure_sfs_acl_mapping
short_description: Configure ACL on interfaces on Dell SmartFabric Services.
description:
    -  This module is used to manage ACL configuration on interfaces.
author: Ranjith Sunkesula <Ranjith_Senkesula@Dellteam.com>
options:
  interface:
    description:
      - Configures the interface parameters.
    type: list
    required: False
  state:
    description:
      - The state the configuration should be left in.
    type: str
    default: present
    required: False
"""
EXAMPLES = '''
Copy below YAML into a playbook (e.g. play.yml) and run as follows:

#$ ansible-playbook -i inventory play.yaml
- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
         - name: Apply Acl on interface
           dellemc.sfs.sfs_acl_mapping:
             interface: [{"name":"ethernet1/1/14:1", "dell-policy:policy-acl-config":{"access-group":[{"role":"ipv4","direction":"in","vrf":"0","name":"uplink-acl"}]}}]   # noqa: E501
           register: result

    - name: Debug the result
      debug: var=result
'''

from ansible_collections.dellemc.sfs.plugins.module_utils.sfs.sfs import SFSConfig, extract_id_value
from ansible_collections.ansible.netcommon.plugins.module_utils.network.restconf import (
    restconf,
)
from ansible.module_utils.basic import AnsibleModule


class SFSAclMapping(SFSConfig):
    def __init__(self):
        argument_spec = {
            'state': {
                'type': 'str',
                'default': "present",
                'required': False
            },
            'name': {
                'type': 'str',
                'required': False
            },
            'primary_addr': {
                'type': 'str',
                'required': False
            },
            'interface': {
                'type': 'list',
                'required': False
            }

        }
        module = AnsibleModule(argument_spec=argument_spec)
        SFSConfig.__init__(self, module, False)
        self.payload_arg_map = {
            'name': 'name',
            'primary-addr': 'primary_addr',
            'interface': 'interface'
        }

        self.path = "ietf-interfaces:interfaces"
        self.redfish_support = False
        self.patch_support = True
        self.content_type = 'application/yang-data+json'
        self.is_get_running = False


if __name__ == "__main__":
    SFSAclMapping().execute_module()
