#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfs_port_breakout
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: sfs_port_breakout
short_description: Configure port breakout on Dell SmartFabric Services.
description:
  - This module is used to manage interface breakout capabilities.
author: Ranjith Sunkesula <Ranjith_Senkesula@Dellteam.com>
options:
  name:
    description:
      - Configures a name.
    type: str
    required: False
  description:
    description:
      - Configures the description string.
    type: str
    required: False
  fanout_profile:
    description:
      - Configures the breakout mode.
    type: str
    required: False
  state:
    description:
      - The state the configuration should be left in.
    type: str
    default: present
    required: False
"""
EXAMPLES = '''
Copy below YAML into a playbook (e.g. play.yml) and run as follows:

#$ ansible-playbook -i inventory play.yaml
- hosts: all
  gather_facts: false
  collections:
    - dellemc.sfs
  tasks:
    - name: Provision Configs
      block:
        - name: Port breakout configuration
          dellemc.sfs.sfs_port_breakout:
            target_port: "VB90DD3:phy-port1/1/24"
            fanout_profile: "HardwareDefault"
            state: 'present'
          register: result

    - name: Debug the result
      debug: var=result
'''


from ansible_collections.dellemc.sfs.plugins.module_utils.sfs.sfs import SFSConfig, extract_id_value
from ansible.module_utils.basic import AnsibleModule


class SFSPortBreakout(SFSConfig):
    def __init__(self):
        argument_spec = {
            'state': {
                'type': 'str',
                'default': "present",
                'required': False
            },
            'description': {
                'type': 'str',
                'required': False
            },
            'name': {
                'type': 'str',
                'required': False
            },
            'target_port': {
                'type': 'str',
                'required': False
            },
            'fanout_profile': {
                'type': 'str',
                'required': False
            }
        }
        module = AnsibleModule(argument_spec=argument_spec)
        SFSConfig.__init__(self, module)
        self.payload_arg_map = {
            'Description': 'description',
            'Name': 'name',
            'FanoutProfile': 'fanout_profile'
        }

        self.path = "Interfaces"
        self.resource_id = self.module.params['target_port']


if __name__ == "__main__":
    SFSPortBreakout().execute_module()
